version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  x86-64-unknown-linux-nightly:
    docker:
      - image: ponylang/ponyup-ci-nightly-builder:latest
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-nightly.bash ${CLOUDSMITH_API_KEY}
      - zulip/status:
          fail_only: true

  shellcheck-init-script:
    docker:
      - image: ponylang/shared-docker-ci-shellcheck:20191008
    steps:
      - checkout
      - run: shellcheck ponyup-init.sh
      - zulip/status:
          fail_only: true

  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: .ci-scripts/install-openssl.sh
      - run: make test
      - run: .ci-scripts/test-bootstrap.sh
      - zulip/status:
          fail_only: true

  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: .ci-scripts/install-openssl.sh
      - run: make test
      - zulip/status:
          fail_only: true

  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify
      - zulip/status:
          fail_only: true

  update-nightly-builder-latest-image:
    docker:
      - image: ponylang/ponyc-ci:docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build nightly-builder Docker image
          command: docker build -t ponylang/ponyup-ci-nightly-builder:latest .ci-dockerfiles/nightly-builder-latest
      - run:
          name: Publish nightly-builder to DockerHub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push ponylang/ponyup-ci-nightly-builder:latest
      - zulip/status:
          fail_only: true

  update-nightly-builder-release-image:
    docker:
      - image: ponylang/ponyc-ci:docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build nightly-builder Docker image
          command: docker build -t ponylang/ponyup-ci-nightly-builder-release .ci-dockerfiles/nightly-builder-release
      - run:
          name: Publish nightly-builder to DockerHub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push ponylang/ponyup-ci-nightly-builder-release
      - zulip/status:
          fail_only: true

workflows:
  version: 2
  every-commit:
    jobs:
      - shellcheck-init-script:
          context: org-global
      - verify-changelog:
          context: org-global
      - vs-ponyc-release:
          context: org-global

  daily-check-for-breakage:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master:
          context: org-global

  create-and-upload-nightly-release:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - x86-64-unknown-linux-nightly:
          context: org-global

  daily-nightly-builder-image-update:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only: master
    jobs:
      - update-nightly-builder-latest-image:
          context: org-global
      - update-nightly-builder-release-image:
          context: org-global
