name: Nightly breakage against ponyc master

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  vs-ponyc-master:
    name: Verify master against ponyc master
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-sslr:latest
    steps:
      - uses: actions/checkout@v1
      - name: Test with a recent ponyc from master
        run: make test
