name: vs-ponyc-latest

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  vs-ponyc-master-macos:
    name: Verify master against ponyc master on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: install pony tools
        run: bash .ci-scripts/macOS-install-nightly-pony-tools.bash
      - name: Test with the most recent ponyc release
        run: |
          export PATH=/tmp/corral/bin/:/tmp/ponyc/bin/:$PATH
          make test
