name: PR

on: pull_request

jobs:
  validate-docker-image-builds:
    name: Validate Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker build
        run: "docker build --pull ."

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-shellcheck:20191008
    steps:
      - uses: actions/checkout@v1
      - name: Shellcheck ponyup-init.sh
        run: shellcheck ponyup-init.sh

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  linux:
    name: Verify PR builds on Linux with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-ssl:release
    steps:
      - uses: actions/checkout@v1
      - name: Test with the most recent ponyc release
        run: make test

  alpine-bootstrap:
    name: Test bootstrapping on Alpine
    runs-on: ubuntu-latest
    container:
        image: ponylang/ponyup-ci-alpine-bootstrap-tester:20191228
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap test
        run: .ci-scripts/test-bootstrap.sh

  fedora-bootstrap:
    name: Test bootstrapping on Fedora
    runs-on: ubuntu-latest
    container:
        image: ponylang/ponyup-ci-fedora-bootstrap-tester:20200101
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap test
        run: |
          export ssl=1.1.x
          .ci-scripts/test-bootstrap.sh

  ubuntu-bootstrap:
    name: Test bootstrapping on Ubuntu
    runs-on: ubuntu-latest
    container:
        image: ponylang/ponyup-ci-ubuntu-bootstrap-tester:20191228
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap test
        run: |
          export ssl=1.1.x
          .ci-scripts/test-bootstrap.sh

  macos:
    name: Verify PR builds on macOS with most recent ponyc release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: brew install pony tools
        run: brew install ponyc pony-stable
      - name: brew install dependencies
        run: brew install coreutils libressl
      - name: Test with the most recent ponyc release
        run: make test

  macos-bootstrap:
    name: Test bootstrapping on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: brew install dependencies
        run: brew install coreutils libressl
      - name: Bootstrap test
        run: .ci-scripts/test-bootstrap.sh

  windows:
    name: Verify PR builds on Windows with the most recent ponyc release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install cygwin
        run: choco install cygwin
      - name: Install pony-stable
        shell: powershell
        run: |
          $PSVersionTable.PSVersion
          $req = [System.Net.WebRequest]::Create("https://bintray.com/pony-language/pony-stable-win/pony-stable/_latestVersion")
          $req.AllowAutoRedirect = $false
          $req.Proxy = $null
          $req.Timeout = 500000
          $req.UserAgent = 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)'
          $res = $req.GetResponse()
          if ($res.StatusCode -eq "Found")
          {
            $latest_url = $res.GetResponseHeader("Location")
            $latest_ver = $latest_url.Substring($latest_url.LastIndexOf("/") + 1)
            $latest_ver = $latest_ver.Substring(0, $latest_ver.LastIndexOf("-"))
            $download_url = "https://bintray.com/pony-language/pony-stable-win/download_file?file_path=" + $latest_ver + "-win64.zip"
            Invoke-WebRequest -Uri $download_url -OutFile pony-stable.zip
            Expand-Archive "pony-stable.zip" -DestinationPath "."
            Rename-Item ($latest_ver + "-win64") "pony-stable"
          }
          else
          {
            Write-Error "Unable to determine latest pony-stable version from BinTray redirect!"
            exit 1
          }
      - name: make
        run: |
          set PATH=\pony-stable\pony-stable\bin;%PATH%
          make test
