name: PR

on: pull_request

jobs:
  validate-docker-image-builds:
    name: Validate Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker build
        run: "docker build ."
