name: PR

on: pull_request

jobs:
  validate-docker-image-builds:
    name: Validate Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker build
        run: "docker build --pull ."

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-shellcheck:20191008
    steps:
      - uses: actions/checkout@v1
      - name: Shellcheck ponyup-init.sh
        run: shellcheck ponyup-init.sh

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  linux:
    name: Verify PR builds on Linux with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-ssl:release
    steps:
      - uses: actions/checkout@v1
      - name: Test with the most recent ponyc release
        run: make test

  alpine-bootstrap:
    name: Test bootstrapping on Alpine
    runs-on: ubuntu-latest
    container:
        image: ponylang/ponyup-ci-alpine-bootstrap-tester:20200503
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap test
        run: .ci-scripts/test-bootstrap.sh

  ubuntu-bootstrap:
    name: Test bootstrapping on Ubuntu
    runs-on: ubuntu-latest
    container:
        image: ponylang/ponyup-ci-ubuntu-bootstrap-tester:20200503
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap test
        run: |
          export ssl=1.1.x
          .ci-scripts/test-bootstrap.sh

  macos:
    name: Verify PR builds on macOS with most recent ponyc release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: install pony tools
        run: bash .ci-scripts/macOS-install-release-pony-tools.bash
      - name: Test with the most recent ponyc release
        run: |
          export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:$PATH"
          make test

  macos-bootstrap:
    name: Test bootstrapping on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: update homebrew
        run: brew update
      - name: brew install dependencies
        run:
          brew install coreutils libressl
      - name: Bootstrap test
        run: .ci-scripts/test-bootstrap.sh
